[package]
name = "r_fetcher"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Test deploy pakage"
authors = ["Alexei.gaponov@gmail.com"]


[dependencies]
rand = "0.8.5"



[profile.dev]
opt-level = 2

[profile.release]
opt-level = 2